post/urls.py
from django.conf.urls import patterns, include, url
from website import views
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', views.home, name='home'),
                       url(r'^register$',views.register, name='register'),
                       url(r'^sign_in$', views.sign_in, name='sign_in'),
                       url(r'^sign_out$', views.sign_out, name='sign_out'),
                       url(r'^post_item$', views.post_item, name='post_item'),
                       url(r'^admin/', include(admin.site.urls)),
                       # temporarily redirect the page //
                       #url(r'^my_items$',views.testHenry, name='my_items'),
                       url(r'^accounts/login/$', views.sign_in),
                       url(r'^search', views.search, name='search'),
                       url(r'^messages$',views.messages, name='messages'),
                       url(r'^password$',views.reset_password, name='password'),
                       url(r'^myItems$',views.goToMyItems, name='myItems'),
                       # JSON api
                       url(r'^api/item$',views.item_messages),
                       url(r'^api/thread$',views.message_thread),
                       url(r'^api/send$', views.send_message),
                       url(r'^api/handshake',views.start_thead),
                       #items page
                       url(r'^item/(?P<item_id>\d+)$',views.item)
                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms.widgets import CheckboxSelectMultiple
from taggit.forms import TagWidget, TagField

class TeachForm(forms.Form):
    def addError(self, message):
        self._errors[NON_FIELD_ERRORS] = self.error_class([message])

class SearchForm(forms.Form):
    q = forms.CharField(
        required=True,
        label = 'Search'
        )
class RegForm(TeachForm):
    firstname = forms.CharField(
        required=True,
        label='First Name'
    )

    lastname = forms.CharField(
        required=True,
        label='Last Name'
    )
    email = forms.EmailField(
        required=True,
        label= 'sjsu email'
    )
    """
    address = forms.CharField(
        required=True,
        label='Street Address'
    )
    """
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(render_value=False),
        label='Password'
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(render_value=False),
        label='Password Confirmation'
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return cleaned_data


class SignInForm(TeachForm):

    signin_email = forms.EmailField(
        required=True,
        label='Email'
    )

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(render_value=False)
    )

class ItemForm(TeachForm):
    # def __init__(self, *args, **kwargs):
    #     super(TeachForm, self).__init__(*args, **kwargs)
    #     for field in self.fields:
    #         self.fields[field].widget.attrs['class'] = 'controls'
    #         print type(self.fields[field].label)

    MY_CHOICES = (
    (False,u'Selling'),
    (True,u'Looking for'),
)

    item_sellOrLookFor = forms.ChoiceField(
                                label= ' I am ',
                                required=True,    
                                choices = MY_CHOICES,
                                )

    CATEGORY_CHOICES = (
        ('Item',u'Item'),
        ('Service/Job',u'Service/Job'),
        ('Housing',u'Housing'),
    )

    item_category = forms.ChoiceField(
                                label= 'Category',
                                required=True,    
                                choices = CATEGORY_CHOICES,
                                )

    item_name= forms.CharField(
		required= True,
        label = 'Name',
        max_length = 80
        # attrs={'class':'special'}
    )

    item_tags = TagField(
        label= 'Tags',
        required = False,
        # widget = TagWidget((attrs={'placeholder': 'Comma separated'}),)
    )
    # item_price= forms.DecimalField(
    #     required= True,
    #     label = 'Price'
    # )
    item_description= forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'placeholder': 'Please include the price in your description.'}),
        label= 'Description'
    )
    item_negotiable= forms.BooleanField(
        required=False,
        label= 'Price Negotiable'
    )

    image_first = forms.FileField(
        label='Upload an image (optional)',
        help_text='max. 42 megabytes',
        required=False
    )

    image_second = forms.FileField(
        label='Upload an image (optional)',
        help_text='max. 42 megabytes',
        required=False
    )

    image_third = forms.FileField(
        label='Upload an image (optional)',
        help_text='max. 42 megabytes',
        required=False
    )

class PasswordResetForm(TeachForm):

    old_password= forms.CharField(
        required= True,
        widget=forms.PasswordInput(render_value=False)
        
    )

    new_password= forms.CharField(
        required= True,
        widget=forms.PasswordInput(render_value=False)
    )

    confirm_new_password= forms.CharField(
        required= True,
        widget=forms.PasswordInput(render_value=False)
    )

website/views.py
# Create your views here.
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.template import RequestContext
# from djagno.template import loader
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
# from lecture.models import Session, SessionTransaction, Question
# import simplejson

from django.db.models import Count
import hashlib
from django.db.models import Q
#from django.utils.timesince import timesince
from django.views.decorators.csrf import csrf_exempt

try: import simplejson as json
except ImportError: import json

from django.contrib.auth.decorators import login_required

from forms import RegForm, SignInForm, ItemForm, SearchForm, PasswordResetForm
from models import Item, Message
from django.core.mail import send_mail

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home(request):
    queries_without_page = request.GET.copy()
    q = request.GET.get('q')
    items = Item.objects.filter(active = True).order_by('timestamp').reverse()
        
    if q:
        items = items.filter(name__icontains=q) | \
                Item.objects.filter(description__icontains=q)
    # check for additional filters
    if request.GET.get('need_or_sold'):
        nos = request.GET.get('need_or_sold').strip()
        if nos != 'unset' and nos != 'both':
            # todo: this looks like it's wrong on the input end.
            # had to reverse to achieve desired functionality
            nos_filter= False if nos == 'needed' else True
            items=items.filter(looking_for=nos_filter)
    
    if request.GET.get('category'):
        cat = request.GET.get('category').strip()
        if cat != 'unset' and cat != 'all':
            items = items.filter(category__icontains=cat)

    if queries_without_page.has_key('page'):
        del queries_without_page['page']


    # max of 500 results
    items = items[:100]
    paginator = Paginator(items, 10) # Show 10 items per page
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        items = paginator.page(paginator.num_pages)
    
    return render_to_response('homepage_default.html', 
            {'items': items, 'user': request.user,
            'queries':queries_without_page})

def sign_in(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    email = password = ''
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['signin_email']
            password = form.cleaned_data['password']
            # hack to use emails only
            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    form.addError(
                        "Your account is not active, please contact the site admin.")
            else:
                form.addError("Your email and/or password were incorrect.")
    else:
        # register
        form = SignInForm()
    return render_to_response(
        'sign_in.html',
        {
            'form': form,
            'user': request.user
        },
        context_instance=RequestContext(request)
    )


def sign_out(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def post_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST,  request.FILES)
        if form.is_valid():
            m_tags = form.cleaned_data['item_tags']
            m = Item(
                name=form.cleaned_data['item_name'],
                # type=form.cleaned_data['item_type'],
                # item_image=request.FILES['item_image'],
                image_first = form.cleaned_data['image_first'],
                image_second= form.cleaned_data['image_second'],
                image_third= form.cleaned_data['image_third'],
                looking_for = True if 'True' == form.cleaned_data['item_sellOrLookFor'] else False,
                category = form.cleaned_data['item_category'],
                #price=form.cleaned_data['item_price'],
                negotiable=form.cleaned_data['item_negotiable'],
                owner=request.user,
                description=form.cleaned_data['item_description']
            )
            m.save()
            print "item has been saved with item_id "+str(m.pk)
            print m_tags
            m.tags.add(*m_tags)
            # return my_items(request)
            return HttpResponseRedirect('/')

    else:
        form = ItemForm()
    return render_to_response('post_item.html', {'form': form, 'user': request.user}, context_instance=RequestContext(request))



def register(request):
    if request.user.is_authenticated():
        return post_item(request)
    user = None
    signinform = SignInForm()
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['email'].find('@sjsu.edu')!=-1:
                user = User(
                    first_name=form.cleaned_data['firstname'],
                    last_name=form.cleaned_data['lastname'],
                    email=form.cleaned_data['email'],
                    username=form.cleaned_data['email']
                )
                user.set_password(form.cleaned_data['password1'])
                try:
                    user.save()
                except IntegrityError:
                    form.addError(user.email + ' is already a member')
                else:
                    user = authenticate(username=form.cleaned_data['email'],
                                        password=form.cleaned_data['password1'])
                    if user is not None:
                        if user.is_active:
                            login(request, user)
                    return HttpResponseRedirect('/')
            else:
                form.addError("You did Not enter a valid email address")
    else:
        form = RegForm()
    return render_to_response(
        'register.html',
        {
        'form': form,
        'signinform': signinform,
        'months': range(1, 12),
        'user': request.user,
        },
        context_instance=RequestContext(request)
    )


def search(request):
    if request.method == 'GET':
        print request.GET
        form = SearchForm(request.GET)
        if form.is_valid:
            pass
            # print "search form is valid"
        q = request.GET.get('q')
        items = Item.objects.filter(active = True)
        
        if q:
            items = items.filter(name__icontains=q) | \
                    Item.objects.filter(description__icontains=q)
        # check for additional filters
        if request.GET.get('need_or_sold'):
            nos = request.GET.get('need_or_sold').strip()
            if nos != 'unset' and nos != 'both':
                # todo: this looks like it's wrong on the input end.
                # had to reverse to achieve desired functionality
                nos_filter= True if nos == 'needed' else False
                items=items.filter(looking_for=nos_filter)
        if request.GET.get('category'):
            cat = request.GET.get('category').strip()
            if cat != 'unset' and cat != 'all':
                items = items.filter(category__icontains=cat)
        return render_to_response('search_results.html', {'items':items, 'q':q, 'user':request.user})

    else:
        return HttpResponseRedirect('/')


@csrf_exempt
def reset_password(request):
    feedback = {'status':None, 'data':None}
    if request.method == 'POST':
        print(request.POST)
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            old_Password=form.cleaned_data['old_password']
            new_Password=form.cleaned_data['new_password']
            confirm_New_Password=form.cleaned_data['confirm_new_password']
            if (new_Password == confirm_New_Password) and request.user.check_password(old_Password):
                request.user.set_password(new_Password)
                request.user.save()
                feedback['status']='OK'
                feedback['data']="Password has been reset successfully."
            else:
                feedback['status']='FAIL'
                feedback['data']="An Error occurred. Password change unsuccessful."
        else:
            feedback['status']='FAIL'
            feedback['data']="An Error occurred. Password change unsuccessful."
            feedback['form'] = 'invalid'

    return HttpResponse(json.dumps(feedback),content_type="application/json")



def remove_listing(request):

    render_to_response('myItems.html')


@login_required
def messages(request):
    if request.user.is_authenticated():
        list_of_my_messages = Message.objects.filter(item__owner=request.user)
        list_of_my_items = Item.objects.filter(owner=User.objects.filter(id=request.user.id)[0])
        print list_of_my_items
        return render_to_response('messages.html', {'items': list_of_my_items, 'messages': list_of_my_messages})
    else:
        raise Http404


# Messages JSON API
@login_required
def item_messages(request):
    # try:
        if request.method == 'GET':
            id=request.GET["id"]
            list_of_messages = Message.objects.filter(
                item__owner=request.user,item__id=id).filter(~Q(sender=request.user)).values(
                'sender','sender__first_name','sender__last_name','sender__email','item','item__name','item__price').order_by().annotate(Count('sender'))

website/templates/errors.html
            {% if form.is_bound and not form.is_valid %}
            <div class="alert alert-error block-message error">
              <div class="errors">
              {% for field in form.visible_fields %}
                {% for error in field.errors %}
                <p>{{ field.label }} : {{ error }}</p>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <p>{{ error }}</p>
              {% endfor %}
              </div>
            </div>
            {% endif %}

website/templates/field.html
      <div class="clearfix">
        {{ field.label_tag }}
        <div class="input">
          {{ field }}
        </div>
      </div>

website/templates/homepage_default.html
{% extends "page.html" %}
{% block main %}

<!-- single line mixed images -->
{% for item in items %}
<div class="row-fluid{%ifequal forloop.counter0 0%} topspace{% endifequal %}"> <!-- begin single line -->
	{% include "item.html" %}
</div><!--end single line -->
	{% empty %}
    	<h3 class="text-center">Sorry, no items found!</h3>
{% endfor %}


<!--pagination -->
<div class="pagination pagination-centered">    
    <ul>    
        {% if items.has_previous %}  
            <li class="prev">
                <a href="{{url_suffix|default:"?page="}}{{items.previous_page_number}}">{{previous_label|default:"&larr; Previous"}}</a>
            </li>
        {% else %}
            <li class="prev disabled">
                <a href="#">{{previous_label|default:"&larr; Previous"}}</a>
            </li>
        {% endif %}
    {% for pagenum in items.paginator.page_range %}    
        <li{% if items.number == pagenum %} class="active"{% endif %}>
            <a href="{{url_suffix|default:"?page="}}{{pagenum}}">{{pagenum}}</a>
        </li>
    {% endfor %}
    {% if hide_next != "true" %}
        {% if items.has_next %}
            <li class="next">
                <a href="{{url_suffix|default:"?page="}}{{items.next_page_number}}">{{next_label|default:"Next &rarr;"}}</a>
            </li>
        {% else %}
            <li class="next disabled">
                <a href="#">{{next_label|default:"Next &rarr;"}}</a>
            </li>
        {% endif %} 
    {% endif %}   
    </ul> 
</div>

{% comment %}

{% if is_paginated %}
{% load i18n %}
<div class="pagination">
    <ul>
    {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}{{ getvars }}{{ hashtag }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
    {% else %}
        <li class="disabled prev"><a href="#">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
    {% endif %}
    {% for page in pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="current page active"><a href="#">{{ page }}</a></li>
            {% else %}
                <li><a href="?page={{ page }}{{ getvars }}{{ hashtag }}" class="page">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
    {% else %}
        <li class="disabled next"><a href="#">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
    {% endif %}
    </ul>
</div>
{% endif %}
{% endcomment %}
{% endblock %}

{% block tail %}
{% if user.is_authenticated%}
<script type="text/javascript">
	$('.modal-body .btn-primary').not('.passModal, #password-reset-form').click(function(event){
		console.log('found');
		var msg = $(event.target.parentNode.parentNode).find('textarea').val();
		var id = $(event.target.parentNode.parentNode).find('input[type=hidden]').attr("name");
		$.post('/api/handshake',{message:msg, item_id:id},function(data){
			console.log('successful');
		});
		$('#myModal'+id).modal('hide');
	 });

		$('.modal-body .btn-primary').not('.passModal, #password-reset-form').click(function(event){
		var id = $(event.target.parentNode.parentNode).find('input[type=hidden]').attr("name");
		$.post('/api/handshake',{item_id:id},function(data){
			console.log('successful call for deleting item function');
		});
		
	});
</script>
{% endif %}
{% endblock %}

website/templates/myItems.html
{% extends "page.html" %}
{% load gravatar %}
{% block main %}





        <div id="myItems">
            {% for item in items %}
                <div class="row-fluid"> <!-- begin single line -->
                    {% include "item.html" %}
                </div>
             {% endfor %}
        </div>





        {% endblock %}

      

website/templates/myProfile.html
{% extends "page.html" %}
{% load gravatar %}
{% block main %}

{% if feedback%}
<div class="row">
  <div class="span12 alert alert-info">
    <ul>
    {% for tidbit in feedback %}
    <li>{{tidbit}}
    {% endfor %}
  </ul>
  </div>
</div>
{% endif %}

<div class="row-fluid">
  <div class="span2">
    <img src="{% gravatar_url user.email %}" class="img-polaroid clearfix" style="height:100px;width:100px" >
  </div>
  <div class="span5">
    <table class="table table-bordered span12 ">
        <tbody>
           <tr>
              <td>Name</td>
              <td>{{user.first_name}} {{user.last_name}}</td>
          </tr>
          <tr>
              <td>username</td>
              <td>{{user.username}} </td>
          </tr>
          <tr>
              <td>MIT email</td>
              <td>{{user.email}}</td>
          </tr>
        </tbody>
    </table>
  </div>
</div>

    <td><a href="#myModal" role="button" class="btn" data-toggle="modal">Reset Password</a> </td>
<!-- Button to trigger modal -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Password Reset</h3>
    </div>
    <div class="modal-body">

        <form accept-charset="UTF-8" action="{% url "profile" %}" class="form-stacked" method="post">
            {% if form.is_bound and not form.is_valid %}
            <div class="alert-message block-message error">
                <div class="errors">
                    {% include "errors.html" %}
                </div>
            </div>
            {% endif %}
            {% for field in form %}{% include "field.html" %}{% endfor %}
            <div class="modal-footer">
                <input class="btn btn-primary" name="commit" type="submit" value="Save new Password">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>

        </form>


    </div>

</div>

{% endblock %}

website/templates/myProfileo.html
{% extends "page.html" %}
{% load gravatar %}
{% block main %}

{% if feedback%}
<div class="row">
  <div class="span12 alert alert-info">
    <ul>
    {% for tidbit in feedback %}
    <li>{{tidbit}}
    {% endfor %}
  </ul>
  </div>
</div>
{% endif %}

<div class="clearfix">
    <img src="{% gravatar_url user.email %}" class="img-polaroid clearfix" style="height:100px;width:100px" >
</div>
<table class="table table-bordered span12 ">
    <tbody>
       <tr>
          <td>Name</td>
          <td>{{user.first_name}} {{user.last_name}}</td>
      </tr>
      <tr>
          <td>username</td>
          <td>{{user.username}} </td>
      </tr>
      <tr>
          <td>MIT email</td>
          <td>{{user.email}}</td>
      </tr>
</tbody>
</table>

    <td><a href="#myModal" role="button" class="btn" data-toggle="modal">Reset Password</a> </td>
<!-- Button to trigger modal -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Password Reset</h3>
    </div>
    <div class="modal-body">

        <form accept-charset="UTF-8" action="{% url "profile" %}" class="form-stacked" method="post">
            {% if form.is_bound and not form.is_valid %}
            <div class="alert-message block-message error">
                <div class="errors">
                    {% include "errors.html" %}
                </div>
            </div>
            {% endif %}
            {% for field in form %}{% include "field.html" %}{% endfor %}
            <div class="modal-footer">
                <input class="btn btn-primary" name="commit" type="submit" value="Save new Password">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>

        </form>


    </div>

</div>

{% endblock %}

website/templates/my_items.html
{% extends "page.html" %}
{% block main %}
<div class="row">
    <div class="span12">
        <h2 class="text-center">my items</h2>
    </div>
    <div class="span6 offset3 columns">
       <table class="table">
           {% for item in items %}
           <tr><td>{{item.item_name}}</td><td>{{item.item_type}}</td></tr>
           {% endfor %}
       </table>
   </div>
</div> 
{% endblock %}

website/templates/page.html
{% load static %}{% load gravatar %}<!DOCTYPE html>

{% comment %} This is the main template{% endcomment %}
<html>
  <head>
    <title>SJSUPost</title>
    <link href="{% get_static_prefix %}css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    <link href="{% get_static_prefix %}css/bootstrap-responsive.css" media="screen" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}css/custom.css">
    <script src="{% get_static_prefix %}js/jquery-1.9.0.min.js" type="text/javascript"></script>
    {% block header %}{% endblock %}
  </head>
  <body>
   <div class="navbar">
  <div class="navbar-inner">
  <div class = "container">
  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
    <a class="brand" href="{% url 'home' %}">SJSUPost</a>
    <div class="nav-collapse collapse">
    <ul class="nav">
        {% if user.is_authenticated %}
        <li><a href="{% url "post_item" %}">Post</a></li>
        <li><a href="{% url "myItems" %}">My Items</a></li>
        {% endif %}
        {% if not user.is_authenticated %}
      <li><a href="{% url "register"%}">Register</a></li>
      {% endif %}
    </ul>
    <ul class="nav pull-right">
      <li class="dropdown">
        <a id="type-dropdown" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">filter<b class="caret"></b></a>
        <ul id="type-dropdown-ul" class="dropdown-menu" role="menu" aria-labelledby="type-dropdown">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">being sold</a></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">needed</a></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">both</a></li>
        </ul>
      </li> 
      <li class="dropdown">
        <a href="#" id="category-dropdown" role="button" class="dropdown-toggle" data-toggle="dropdown">category<b class="caret"></b></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="category-dropdown" id="category-dropdown-ul">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">item</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">service/Job</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">housing</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">all</a></li>

        </ul>
      </li>
      <form class="navbar-search" accept-charset="UTF-8" action="{% url "search" %}"  method="get">
          <input id="id_q" type="text" class="search-query" name ="q" placeholder="Search" data-provide="typeahead" data-source="['one','two','three']">
          <input type="hidden" id="filter-need_or_sold" name="need_or_sold" value="unset"/>
          <input type="hidden" id="filter-category" name="category" value="unset"/>
           <!-- <span class="add-on"> <i class="icon-search"></i> </span> -->
      </form>
      {% if user.is_authenticated %}
      <li class="dropdown">
        <a href="#" role="button" class="dropdown-toggle gravatarDropdown" data-toggle="dropdown"><img src="{% gravatar_url user.email %}" class="img-polaroid " style="height:15px;width:15px" ></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="category-dropdown" id="category-dropdown-ul">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "sign_out" %}">Sign Out</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#passModal" data-toggle="modal">Reset Password</a></li>
        </ul>
      </li>
      {% include "password_reset.html" %}

        {% else %}
        <li><a href="{% url "register" %}">Sign In</a></li>

        {% endif %}
    </ul>


    </div>
  </div>
  </div>
</div>
    <div class="main container">
{% block main %}{% endblock %}
    </div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster
    TODO:minify -->
    <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
    <!--script src="{% get_static_prefix %}js/jquery.js"></script-->
    <script src="{% get_static_prefix %}js/bootstrap-transition.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-alert.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-modal.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-dropdown.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-scrollspy.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-tab.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-tooltip.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-popover.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-button.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-collapse.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-carousel.js"></script>
    <script src="{% get_static_prefix %}js/bootstrap-typeahead.js"></script>

    <script src="{% get_static_prefix %}js/search.js"></script>
    {% block tail %}{% endblock %}
    <footer>
      <div class="footer">
       <div class="container narrow row-fluid">
		SJSUPost is not affiliated with SJSU 
       </div>
      </div>
  </footer>
  </body>
</html>

website/templates/post_item.html
{% extends "page.html" %}
{% block main %}
<div class="row">
<form accept-charset="UTF-8" action="{% url "post_item" %}" class="span5 offset2 form-horizontal" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% if form.is_bound and not form.is_valid %}
	<div class="alert-message block-message error">
		<div class="errors">
			{% include "errors.html" %}
		</div>
	</div>
	{% endif %}
	<!-- {% comment %}{% for field in form %}{% include "field.html" %}{% endfor %}{% endcomment %} -->
	{% for field in form %}
	<fieldset class="control-group">
	    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
	    <div class="controls">
	        {{ field }}
	        <p class="help-text">{{ field.help_text }} </p>
	    </div>
	</fieldset>
	{% endfor %}

	<div class="actions">
		<input class="btn btn-primary pull-right" name="commit" type="submit" value="Post">
	</div>
</form>
</div>
{% endblock %}

website/templates/search.html
{% extends "page.html" %}
{% block main %}
{{form.as_p}}
{% endblock %}